language: python
python:
  - "3.4"
  - "3.5"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install pipenv
  - pipenv install --dev --system
script:
  - pipenv run python setup.py test
  - pipenv run pytest --cov
after_success:
  - pipenv run codecov