language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
cache: pip
dist: xenial
install:
  - pip install pipenv
  - pipenv install --dev --system
script:
  - pipenv run python setup.py test
  - pipenv run pytest --cov
after_success:
  - pipenv run codecov