language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
cache: pip
dist: xenial
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
install:
  - pip install pipenv
  - pipenv install --dev --system
script:
  - pipenv run -- pytest -n auto --boxed --mypy --ignore=setup.py
  - pipenv run -- pytest --cov=defer
  - pipenv run -- coverage xml
after_success:
  - pipenv run -- codecov
  - pipenv run -- python-codacy-coverage
