language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
cache: pip
dist: xenial
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pipenv run -- pytest -n auto --boxed --mypy --ignore=setup.py
  - pipenv run -- pytest --cov=defer
after_success:
  - pipenv run -- codecov